// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: katar.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Katar_Publish_FullMethodName = "/katar.Katar/Publish"
)

// KatarClient is the client API for Katar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KatarClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type katarClient struct {
	cc grpc.ClientConnInterface
}

func NewKatarClient(cc grpc.ClientConnInterface) KatarClient {
	return &katarClient{cc}
}

func (c *katarClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, Katar_Publish_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KatarServer is the server API for Katar service.
// All implementations must embed UnimplementedKatarServer
// for forward compatibility
type KatarServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	mustEmbedUnimplementedKatarServer()
}

// UnimplementedKatarServer must be embedded to have forward compatible implementations.
type UnimplementedKatarServer struct {
}

func (UnimplementedKatarServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedKatarServer) mustEmbedUnimplementedKatarServer() {}

// UnsafeKatarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KatarServer will
// result in compilation errors.
type UnsafeKatarServer interface {
	mustEmbedUnimplementedKatarServer()
}

func RegisterKatarServer(s grpc.ServiceRegistrar, srv KatarServer) {
	s.RegisterService(&Katar_ServiceDesc, srv)
}

func _Katar_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatarServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Katar_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatarServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Katar_ServiceDesc is the grpc.ServiceDesc for Katar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Katar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "katar.Katar",
	HandlerType: (*KatarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Katar_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "katar.proto",
}
